### ISSUE TITLE
Fails to run on python 3.6

### ISSUE THREAD

**Issue by justin8** [dionysio/haveibeenpwned_lastpass#2]
I'm running python 3.6.1, I tried to do `pip install -r requirements.txt`, they all installed without issues, but on run I get:

```
Traceback (most recent call last):
  File "have_i_though.py", line 6, in <module>
    from user_input import _user_get_lastpass_vault, _user_get_mode, get_lastpass_vault
  File "/Users/justin/git/haveibeenpwned_lastpass/user_input.py", line 6, in <module>
    from lastpass import exceptions
  File "/Users/justin/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lastpass/__init__.py", line 1, in <module>
    from .vault import Vault
  File "/Users/justin/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lastpass/vault.py", line 3, in <module>
    from . import parser
  File "/Users/justin/.pyenv/versions/3.6.1/lib/python3.6/site-packages/lastpass/parser.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by justin8** [comment]
It appears my python 3.6 install broke itself in a recent OSX upgrade. It's working fine now.
