### ISSUE TITLE
Error getting lastpass vault

### ISSUE THREAD

**Issue by AbsoluteDestiny** [dionysio/haveibeenpwned_lastpass#3]
On windows python 3.6 it errors on vault = _user_get_lastpass_vault()

No 2FA on the account, just email and password.

**Comment by dionysio** [comment]
Thanks for reporting. Can you please post the exception and traceback it throws?

**Comment by AbsoluteDestiny** [comment]
Not much in it:

```
Unexpected error occurred:
Traceback (most recent call last):
  File ".\have_i_though.py", line 14, in have_i_though
    vault = _user_get_lastpass_vault()
  File "C:\Users\AbsoluteDestiny\haveibeenpwned_lastpass\user_input.py", line 44, in _user_get_lastpass_vault
    sys.exit()
```

I get the same error from the linux subsytem for windows, except on that I'm asked for my email/password a second time before it fails. I assume this is actually an upstream lastpass-python issue?

**Comment by dionysio** [comment]
Huh, there should be a line which says `Couldn't log you in due to an error:` just after asking you the second time for login/pw, do you see it?
